language: rust

branches:
  only:
    - master

services:
  - docker

git:
  depth: false

rust:
  - stable
  - nightly
cache: cargo
jobs:
  include:
    - stage: build
      before_script:
        - export DOCKER_TAG=$(git describe --always)
      script:
        - ./push_image.sh
    - stage: test
      script:
        - cargo test --verbose --all
    - stage: deploy
      script:
        - docker push $DOCKER_REPO/expense_calculator:latest
        - docker push $DOCKER_REPO/expense_calculator:"$DOCKER_TAG"
