language: rust

branches:
  only:
    - master

services:
  - docker

git:
  depth: false

rust:
  - stable
cache: cargo
jobs:
  include:
    - stage: build
      before_script:
        - export DOCKER_TAG=$(git describe --always)
      script:
        - ./build.sh
    - stage: test
      script:
        - cargo test --verbose --all
    - stage: publish
      script:
        - ./publish.sh
