language: rust

branches:
  only:
    - master

services:
  - docker

rust:
  - stable
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

deploy:
  provider: script
  script: bash push_image.sh
  on:
    branch: master

