language: rust

branches:
  only:
    - master

services:
  - docker

git:
  depth: false

rust:
  - stable
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

before_deploy:
  - git fetch --tags
  - export DOCKER_TAG=$(git describe --always)

deploy:
  provider: script
  script: bash push_image.sh
  skip_cleanup: true
  on:
    branch: master
